[project]
name = "obsi-sync-11ty"
version = "0.1.0"
description = "Helper scripts to track tagged obsidian notes inwebsite repo."
authors = ["Fabio Meier <fabitosh@gmail.com>"]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyyaml>=6.0.2",
    "pytest>=8.2.0",
]
